import Head from "next/head";
import Image from "next/image";
import ColorToggle from "@/components/ColorToggle";
import AspectRatio from "@mui/joy/AspectRatio";
import Box from "@mui/joy/Box";
import Button from "@mui/joy/Button";
import Card from "@mui/joy/Card";
import IconButton from "@mui/joy/ICONBUTTON";
import Typography from "@mui/joy/Typography";
import BookmarkAdd from "@mui/icons-material/BookmarkAddOutlined";
import { Sheet } from "@mui/joy";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Sheet sx={{ width: "100vw", height: "100vh" }}>
          <Typography level="h1">Home</Typography>
          <ColorToggle />
          <Card variant="outlined" sx={{ width: 700, height: 500 }}>
            <Typography level="h2" fontSize="md" sx={{ mb: 0.5 }}>
              Yosemite National Park
            </Typography>
            <Typography level="body2">April 24 to May 02, 2021</Typography>
            <IconButton
              aria-label="bookmark Bahamas Islands"
              variant="plain"
              color="neutral"
              size="sm"
              sx={{ position: "absolute", top: "0.5rem", right: "0.5rem" }}
            >
              <BookmarkAdd />
            </IconButton>
            <AspectRatio minHeight="120px" maxHeight="200px" sx={{ my: 2 }}>
              <img
                src="https://images.unsplash.com/photo-1527549993586-dff825b37782?auto=format&fit=crop&w=700"
                srcSet="https://images.unsplash.com/photo-1527549993586-dff825b37782?auto=format&fit=crop&w=700&dpr=2 2x"
                loading="lazy"
                alt=""
              />
            </AspectRatio>
            <Box sx={{ display: "flex" }}>
              <div>
                <Typography level="body3">Total price:</Typography>
                <Typography fontSize="lg" fontWeight="lg">
                  $2,900
                </Typography>
              </div>
              <Button
                variant="solid"
                size="sm"
                color="primary"
                aria-label="Explore Bahamas Islands"
                sx={{ ml: "auto", fontWeight: 600 }}
              >
                Explore
              </Button>
              <Button
                variant="solid"
                size="sm"
                color="neutral"
                aria-label="Explore Bahamas Islands"
                sx={{ ml: "auto", fontWeight: 600 }}
              >
                Explore
              </Button>
              <Button
                variant="solid"
                size="sm"
                color="warning"
                aria-label="Explore Bahamas Islands"
                sx={{ ml: "auto", fontWeight: 600 }}
              >
                Explore
              </Button>
              <Button
                variant="solid"
                size="sm"
                color="info"
                aria-label="Explore Bahamas Islands"
                sx={{ ml: "auto", fontWeight: 600 }}
              >
                Explore
              </Button>
              <Button
                variant="solid"
                size="sm"
                color="success"
                aria-label="Explore Bahamas Islands"
                sx={{ ml: "auto", fontWeight: 600 }}
              >
                Explore
              </Button>
              <Button
                variant="solid"
                size="sm"
                color="danger"
                aria-label="Explore Bahamas Islands"
                sx={{ ml: "auto", fontWeight: 600 }}
              >
                Explore
              </Button>
            </Box>
          </Card>
        </Sheet>
      </main>
    </>
  );
}
